<a href="https://colab.research.google.com/github/spvedantham/py/blob/main/X_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**My First py program in colab this year (2026)**

In [ ]:
import numpy as np
np.arange(10,20,2)


array([10, 12, 14, 16, 18])

In [ ]:
a = np.arange(100,50,-23)
print(a)

[100  77  54]


In [18]:
import numpy as np
a = np.arange(15).reshape(3,5)
print("a = ", a)
print("a.shape =" , a.shape)
print("a.ndim = " , a.ndim)
print("a.dtype.name = " , a.dtype.name)
print("a.itemsize = ", a.itemsize)
print("a.size = ", a.size)
print("type(a) = ", type(a))

a =  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a.shape = (3, 5)
a.ndim =  2
a.dtype.name =  int64
a.itemsize =  8
a.size =  15
type(a) =  <class 'numpy.ndarray'>


In [19]:
b=np.array([6,7,8])
print("b = ", b)
print("type(b) = ", type(b))

b =  [6 7 8]
type(b) =  <class 'numpy.ndarray'>


# **Several ways to create array using numpy**

In [8]:
import numpy as np

# create regular python array
a = np.array([2,3,4])                 # int array
print ("a = ", a)
print("a.dtype = ", a.dtype)
b = np.array([1.2,3.5,5.1])           # float array
print("b = ", b)
print("b.dtype = ", b.dtype)

# function zeros
c= np.zeros((3,5))
print ("with zeros function c = \n", c)

# function ones
d = np.ones((2,3,4), dtype=np.int16)
print("with ones function d=\n", d)

# function empty
e = np.empty((2,3))
print("with empty function e =\n", e)

e = np.empty((2,3), dtype=np.int16)
print("with empty function e =\n", e)


a =  [2 3 4]
a.dtype =  int64
b =  [1.2 3.5 5.1]
b.dtype =  float64
with zeros function c = 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
with ones function d=
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
with empty function e =
 [[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
with empty function e =
 [[-11680    784      0]
 [     0      0      0]]


# **Basic operations on arrays**

In [6]:
# Arithmetic operations

import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print("a = ", a)
print("b = ", b)

c = a - b
print("c = a - b i.e. \n", c)

d = b**2
print("d = ", d)

f = 10 * np.sin(a)
print("f = ", f)

a < 35


a =  [20 30 40 50]
b =  [0 1 2 3]
c = a - b i.e. 
 [20 29 38 47]
d =  [0 1 4 9]
f =  [ 9.12945251 -9.88031624  7.4511316  -2.62374854]


array([ True,  True, False, False])

In [15]:
# Basic Operators

A = np.array([ [1,1], [0,1]])
B = np.array([[2, 0], [3,4]])

print("\n A = \n", A)
print("\n B = \n", B)
print("\n\n")
print("A ^ B = \n ", A * B)
print("A @ B = \n", A @ B),


 A = 
 [[1 1]
 [0 1]]

 B = 
 [[2 0]
 [3 4]]



A ^ B = 
  [[2 0]
 [0 4]]
A @ B = 
 [[5 4]
 [3 4]]


(None,)