<a href="https://colab.research.google.com/github/spvedantham/py/blob/main/X_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**My First py program in colab this year (2026)**

In [ ]:
import numpy as np
np.arange(10,20,2)


array([10, 12, 14, 16, 18])

In [ ]:
a = np.arange(100,50,-23)
print(a)

[100  77  54]


In [18]:
import numpy as np
a = np.arange(15).reshape(3,5)
print("a = ", a)
print("a.shape =" , a.shape)
print("a.ndim = " , a.ndim)
print("a.dtype.name = " , a.dtype.name)
print("a.itemsize = ", a.itemsize)
print("a.size = ", a.size)
print("type(a) = ", type(a))

a =  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a.shape = (3, 5)
a.ndim =  2
a.dtype.name =  int64
a.itemsize =  8
a.size =  15
type(a) =  <class 'numpy.ndarray'>


In [19]:
b=np.array([6,7,8])
print("b = ", b)
print("type(b) = ", type(b))

b =  [6 7 8]
type(b) =  <class 'numpy.ndarray'>
